### ISSUE TITLE
Errores en README.md

### ISSUE THREAD

**Issue by alu0100845235** [alu0100818208/tareas-iniciales-alu0100818208#2]
En el fichero de información de proyecto (README.md) he visto los siguiente errores:
- Mencionas una asignatura que no corresponde.
- Te falta nombrar alguna herramienta en la lista

Deberías modificarlo :goberserk: .

**Comment by alu0100818208** [comment]
Ya he corregido dichos fallos. Lo verás en el commit https://github.com/alu0100818208/tareas-iniciales-alu0100818208/commit/aaf1bfc454e2a7a453b15bd4091bcaae6b75f3a2. Gracias por la observación. :+1:

**Comment by alu0100818208** [comment]
Ya he corregido dichos fallos. Lo verás en el commit https://github.com/alu0100818208/tareas-iniciales-alu0100818208/commit/49b9a94c7cbe7339f71e6e81c32b67001687fb56. Gracias por la observación. :+1:
